version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build: 
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run start-dev"
    env_file: '.env'
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: 'timeout 2 bash -c "</dev/tcp/localhost/27017"'
      interval: 5s
      timeout: 5s
      retries: 10
    # logging:
    #   driver: none